# Generated by Django 2.2.12 on 2020-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=30)),
                ('domain', models.CharField(default='', help_text='university domain', max_length=20)),
                ('alpha_two_code', models.CharField(default='', help_text='two letter alpha 2 code', max_length=2)),
                ('web_page', models.CharField(blank=True, max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
